[theme]
base = "dark"
primaryColor = "#E10600"
backgroundColor = "#0F0F14"
secondaryBackgroundColor = "#1B1B24"
textColor = "#EDEDF2"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
